# Generated by Django 5.1.5 on 2025-02-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_testsession_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
